version: '3'
services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        environment:
            APP_NAME: Test-app
            APP_DEBUG: "true"
            APP_URL:
            APP_URL_VIEW:
            APP_TIMEZONE: UTC

            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: db
            DB_USERNAME: root
            DB_PASSWORD: 12345
            DB_STRICT_MODE: "false"

            SESSION_DRIVER: redis
            SESSION_LIFETIME: 525600
            REDIS_CLIENT: predis
            REDIS_HOST: redis
            REDIS_PORT: 6379
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    db:
        image: mysql:5.7.22
        restart: unless-stopped
        tty: true
        ports:
            - "3308:3306"
        environment:
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: 12345
        volumes:
            - dbdata:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network


    redis:
        image: docker.io/bitnami/redis:6.0
        environment:
            ALLOW_EMPTY_PASSWORD: 'yes'
            # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        volumes:
            - redis_data:/bitnami/redis/data
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
    redis_data:
